import { Emoji } from "../models/Emoji";

const combinations: Record<string, Emoji[]> = {
  A: [
    { description: "alien", emoji: "👽" },
    { description: "artist", emoji: "🧑‍🎨" },
    { description: "astronaut", emoji: "🧑‍🚀" },
    { description: "ant", emoji: "🐜" },
    { description: "avocado", emoji: "🥑" },
    { description: "ambulance", emoji: "🚑" },
    { description: "automobile", emoji: "🚗" },
    { description: "anchor", emoji: "⚓" },
    { description: "airplane", emoji: "✈️" },
    { description: "accordion", emoji: "🪗" },
    { description: "abacus", emoji: "🧮" },
    { description: "atom", emoji: "⚛️" },
  ],
  B: [
    { description: "brain", emoji: "🧠" },
    { description: "bone", emoji: "🦴" },
    { description: "baby", emoji: "👶" },
    { description: "boy", emoji: "👦" },
    { description: "bison", emoji: "🦬" },
    { description: "boar", emoji: "🐗" },
    { description: "bat", emoji: "🦇" },
    { description: "bear", emoji: "🐻" },
    { description: "badger", emoji: "🦡" },
    { description: "bird", emoji: "🐦" },
    { description: "blowfish", emoji: "🐡" },
    { description: "butterfly", emoji: "🦋" },
    { description: "bug", emoji: "🐛" },
    { description: "beetle", emoji: "🪲" },
    { description: "bouquet", emoji: "💐" },
    { description: "blossom", emoji: "🌼" },
    { description: "banana", emoji: "🍌" },
    { description: "blueberries", emoji: "🫐" },
    { description: "broccoli", emoji: "🥦" },
    { description: "bread", emoji: "🍞" },
    { description: "bagel", emoji: "🥯" },
    { description: "bacon", emoji: "🥓" },
    { description: "burrito", emoji: "🌯" },
    { description: "butter", emoji: "🧈" },
    { description: "beach", emoji: "🏖️" },
    { description: "brick", emoji: "🧱" },
    { description: "bank", emoji: "🏦" },
    { description: "bus", emoji: "🚌" },
    { description: "bicycle", emoji: "🚲" },
    { description: "balloon", emoji: "🎈" },
    { description: "baseball", emoji: "⚾" },
    { description: "basketball", emoji: "🏀" },
    { description: "bowling", emoji: "🎳" },
    { description: "badminton", emoji: "🏸" },
    { description: "bullseye", emoji: "🎯" },
    { description: "backpack", emoji: "🎒" },
    { description: "boot", emoji: "👢" },
    { description: "bell", emoji: "🔔" },
    { description: "banjo", emoji: "🪕" },
    { description: "battery", emoji: "🔋" },
    { description: "books", emoji: "📚" },
    { description: "briefcase", emoji: "💼" },
    { description: "boomerang", emoji: "🪃" },
    { description: "bed", emoji: "🛏️" },
    { description: "bath", emoji: "🛁" },
    { description: "broom", emoji: "🧹" },
    { description: "basket", emoji: "🧺" },
    { description: "bucket", emoji: "🪣" },
    { description: "blue", emoji: "🔵" },
    { description: "brown", emoji: "🟤" },
    { description: "black", emoji: "⚫" },
  ],
  C: [
    { description: "cold", emoji: "🥶" },
    { description: "cowboy", emoji: "🤠" },
    { description: "clapping", emoji: "👏" },
    { description: "chef", emoji: "🧑‍🍳" },
    { description: "cat", emoji: "🐈" },
    { description: "cow", emoji: "🐄" },
    { description: "camel", emoji: "🐪" },
    { description: "chicken", emoji: "🐔" },
    { description: "crocodile", emoji: "🐊" },
    { description: "cactus", emoji: "🌵" },
    { description: "cherries", emoji: "🍒" },
    { description: "coconut", emoji: "🥥" },
    { description: "carrot", emoji: "🥕" },
    { description: "cucumber", emoji: "🥒" },
    { description: "cheese", emoji: "🧀" },
    { description: "cooking", emoji: "🍳" },
    { description: "curry", emoji: "🍛" },
    { description: "crab", emoji: "🦀" },
    { description: "cookie", emoji: "🍪" },
    { description: "cupcake", emoji: "🧁" },
    { description: "chocolate", emoji: "🍫" },
    { description: "candy", emoji: "🍬" },
    { description: "chopsticks", emoji: "🥢" },
    { description: "castle", emoji: "🏰" },
    { description: "canoe", emoji: "🛶" },
    { description: "cloud", emoji: "☁️" },
    { description: "cyclone", emoji: "🌀" },
    { description: "coat", emoji: "🧥" },
    { description: "crown", emoji: "👑" },
    { description: "camera", emoji: "📷" },
    { description: "candle", emoji: "🕯️" },
    { description: "coin", emoji: "🪙" },
    { description: "crayon", emoji: "🖍️" },
    { description: "chair", emoji: "🪑" },
  ],
  D: [
    { description: "dog", emoji: "🐕" },
    { description: "deer", emoji: "🦌" },
    { description: "dove", emoji: "🕊️" },
    { description: "duck", emoji: "🦆" },
    { description: "dodo", emoji: "🦤" },
    { description: "dragon", emoji: "🐉" },
    { description: "dolphin", emoji: "🐬" },
    { description: "dumpling", emoji: "🥟" },
    { description: "doughnut", emoji: "🍩" },
    { description: "droplet", emoji: "💧" },
    { description: "down", emoji: "⬇️" },
    { description: "dress", emoji: "👗" },
    { description: "drum", emoji: "🥁" },
    { description: "DNA", emoji: "🧬" },
    { description: "door", emoji: "🚪" },
  ],
  E: [
    { description: "ear", emoji: "👂" },
    { description: "eyes", emoji: "👀" },
    { description: "elf", emoji: "🧝" },
    { description: "ewe", emoji: "🐑" },
    { description: "elephant", emoji: "🐘" },
    { description: "eagle", emoji: "🦅" },
    { description: "egg", emoji: "🥚" },
    { description: "envelope", emoji: "✉️" },
    { description: "e-mail", emoji: "📧" },
    { description: "elevator", emoji: "🛗" },
  ],
  F: [
    { description: "face", emoji: "🙂" },
    { description: "foot", emoji: "🦶" },
    { description: "farmer", emoji: "🧑‍🌾" },
    { description: "firefighter", emoji: "🧑‍🚒" },
    { description: "fairy", emoji: "🧚" },
    { description: "fox", emoji: "🦊" },
    { description: "feather", emoji: "🪶" },
    { description: "flamingo", emoji: "🦩" },
    { description: "frog", emoji: "🐸" },
    { description: "fish", emoji: "🐟" },
    { description: "flatbread", emoji: "🫓" },
    { description: "falafel", emoji: "🧆" },
    { description: "factory", emoji: "🏭" },
    { description: "fountain", emoji: "⛲" },
    { description: "fire engine", emoji: "🚒" },
    { description: "ferry", emoji: "⛴️" },
    { description: "fire", emoji: "🔥" },
    { description: "floppy disk", emoji: "💾" },
    { description: "flag", emoji: "🇳🇿" },
  ],
  G: [
    { description: "ghost", emoji: "👻" },
    { description: "girl", emoji: "👧" },
    { description: "guard", emoji: "💂" },
    { description: "genie", emoji: "🧞" },
    { description: "gorilla", emoji: "🦍" },
    { description: "guide dog", emoji: "🦮" },
    { description: "goat", emoji: "🐐" },
    { description: "giraffe", emoji: "🦒" },
    { description: "grapes", emoji: "🍇" },
    { description: "garlic", emoji: "🧄" },
    { description: "globe", emoji: "🌏" },
    { description: "glasses", emoji: "👓" },
    { description: "goggles", emoji: "🥽" },
    { description: "gloves", emoji: "🧤" },
    { description: "gem", emoji: "💎" },
    { description: "guitar", emoji: "🎸" },
    { description: "gear", emoji: "⚙️" },
    { description: "green", emoji: "🟢" },
  ],
  H: [
    { description: "heart", emoji: "❤️" },
    { description: "hand", emoji: "🖐️" },
    { description: "horse", emoji: "🐎" },
    { description: "hippopotamus", emoji: "🦛" },
    { description: "hamster", emoji: "🐹" },
    { description: "hedgehog", emoji: "🦔" },
    { description: "honeybee", emoji: "🐝" },
    { description: "hamburger", emoji: "🍔" },
    { description: "honey", emoji: "🍯" },
    { description: "hut", emoji: "🛖" },
    { description: "house", emoji: "🏠" },
    { description: "hospital", emoji: "🏥" },
    { description: "helicopter", emoji: "🚁" },
    { description: "hourglass", emoji: "⏳" },
    { description: "handbag", emoji: "👜" },
    { description: "hat", emoji: "👒" },
    { description: "headphones", emoji: "🎧" },
    { description: "hammer", emoji: "🔨" },
  ],
  I: [
    { description: "ice cream", emoji: "🍨" },
    { description: "ice", emoji: "🧊" },
    { description: "ice hockey", emoji: "🏒" },
    { description: "ice skate", emoji: "⛸️" },
    { description: "infinity", emoji: "♾️" },
  ],
  J: [
    { description: "judge", emoji: "🧑‍⚖️" },
    { description: "joystick", emoji: "🕹️" },
    { description: "joker", emoji: "🃏" },
    { description: "jeans", emoji: "👖" },
    { description: "jandal", emoji: "🩴" },
  ],
  K: [
    { description: "koala", emoji: "🐨" },
    { description: "kangaroo", emoji: "🦘" },
    { description: "kiwi fruit", emoji: "🥝" },
    { description: "kite", emoji: "🪁" },
    { description: "keyboard", emoji: "⌨️" },
    { description: "keyboard", emoji: "🎹" },
    { description: "key", emoji: "🔑" },
  ],
  L: [
    { description: "leg", emoji: "🦵" },
    { description: "lungs", emoji: "🫁" },
    { description: "lion", emoji: "🦁" },
    { description: "leopard", emoji: "🐆" },
    { description: "llama", emoji: "🦙" },
    { description: "lizard", emoji: "🦎" },
    { description: "lady bug", emoji: "🐞" },
    { description: "lemon", emoji: "🍋" },
    { description: "lobster", emoji: "🦞" },
    { description: "lollipop", emoji: "🍭" },
    { description: "locomotive", emoji: "🚂" },
    { description: "lab coat", emoji: "🥼" },
    { description: "lipstick", emoji: "💄" },
    { description: "laptop", emoji: "💻" },
    { description: "left", emoji: "⬅️" },
    { description: "light bulb", emoji: "💡" },
    { description: "ladder", emoji: "🪜" },
  ],
  M: [
    { description: "mouth", emoji: "👄" },
    { description: "man", emoji: "👨" },
    { description: "mechanic", emoji: "🧑‍🔧" },
    { description: "mage", emoji: "🧙" },
    { description: "mermaid", emoji: "🧜‍♀️" },
    { description: "monkey", emoji: "🐒" },
    { description: "mammoth", emoji: "🦣" },
    { description: "mouse", emoji: "🐁" },
    { description: "microbe", emoji: "🦠" },
    { description: "melon", emoji: "🍈" },
    { description: "mango", emoji: "🥭" },
    { description: "mushroom", emoji: "🍄" },
    { description: "mountain", emoji: "⛰️" },
    { description: "motorcycle", emoji: "🏍️" },
    { description: "magic", emoji: "🪄" },
    { description: "music", emoji: "🎵" },
    { description: "microphone", emoji: "🎤" },
    { description: "magnifying glass", emoji: "🔍" },
    { description: "magnet", emoji: "🧲" },
    { description: "microscope", emoji: "🔬" },
    { description: "mirror", emoji: "🪞" },
  ],
  N: [
    { description: "nail polish", emoji: "💅" },
    { description: "nose", emoji: "👃" },
    { description: "ninja", emoji: "🥷" },
    { description: "night", emoji: "🌃" },
    { description: "necktie", emoji: "👔" },
    { description: "notebook", emoji: "📓" },
    { description: "newspaper", emoji: "📰" },
  ],
  O: [
    { description: "ogre", emoji: "👹" },
    { description: "OK", emoji: "👌" },
    { description: "orangutan", emoji: "🦧" },
    { description: "ox", emoji: "🐂" },
    { description: "otter", emoji: "🦦" },
    { description: "owl", emoji: "🦉" },
    { description: "octopus", emoji: "🐙" },
    { description: "olive", emoji: "🫒" },
    { description: "onion", emoji: "🧅" },
    { description: "office", emoji: "🏢" },
    { description: "orange", emoji: "🟠" },
  ],
  P: [
    { description: "person", emoji: "🧑" },
    { description: "pilot", emoji: "🧑‍✈️" },
    { description: "police officer", emoji: "👮" },
    { description: "prince", emoji: "🤴" },
    { description: "princess", emoji: "👸" },
    { description: "poodle", emoji: "🐩" },
    { description: "pig", emoji: "🐖" },
    { description: "polar bear", emoji: "🐻‍❄️" },
    { description: "panda", emoji: "🐼" },
    { description: "penguin", emoji: "🐧" },
    { description: "peacock", emoji: "🦚" },
    { description: "parrot", emoji: "🦜" },
    { description: "plant", emoji: "🪴" },
    { description: "pineapple", emoji: "🍍" },
    { description: "pear", emoji: "🍐" },
    { description: "peach", emoji: "🍑" },
    { description: "potato", emoji: "🥔" },
    { description: "peanuts", emoji: "🥜" },
    { description: "pretzel", emoji: "🥨" },
    { description: "pancakes", emoji: "🥞" },
    { description: "pizza", emoji: "🍕" },
    { description: "popcorn", emoji: "🍿" },
    { description: "pie", emoji: "🥧" },
    { description: "puzzle", emoji: "🧩" },
    { description: "purse", emoji: "👛" },
    { description: "pencil", emoji: "✏️" },
    { description: "pen", emoji: "🖊️" },
    { description: "paintbrush", emoji: "🖌️" },
    { description: "petri dish", emoji: "🧫" },
    { description: "purple", emoji: "🟣" },
  ],
  Q: [{ description: "queen", emoji: "👸" }],
  R: [
    { description: "robot", emoji: "🤖" },
    { description: "raccoon", emoji: "🦝" },
    { description: "ram", emoji: "🐏" },
    { description: "rhinoceros", emoji: "🦏" },
    { description: "rat", emoji: "🐀" },
    { description: "rabbit", emoji: "🐇" },
    { description: "rooster", emoji: "🐓" },
    { description: "rose", emoji: "🌹" },
    { description: "rock", emoji: "🪨" },
    { description: "roller coaster", emoji: "🎢" },
    { description: "roller skate", emoji: "🛼" },
    { description: "rocket", emoji: "🚀" },
    { description: "rainbow", emoji: "🌈" },
    { description: "ribbon", emoji: "🎀" },
    { description: "rugby", emoji: "🏉" },
    { description: "ring", emoji: "💍" },
    { description: "right", emoji: "➡️" },
    { description: "red", emoji: "🔴" },
  ],
  S: [
    { description: "skull", emoji: "💀" },
    { description: "student", emoji: "🧑‍🎓" },
    { description: "scientist", emoji: "🧑‍🔬" },
    { description: "singer", emoji: "🧑‍🎤" },
    { description: "Santa Claus", emoji: "🎅" },
    { description: "superhero", emoji: "🦸" },
    { description: "supervillain", emoji: "🦹" },
    { description: "sloth", emoji: "🦥" },
    { description: "swan", emoji: "🦢" },
    { description: "snake", emoji: "🐍" },
    { description: "seal", emoji: "🦭" },
    { description: "shark", emoji: "🦈" },
    { description: "shell", emoji: "🐚" },
    { description: "snail", emoji: "🐌" },
    { description: "spider", emoji: "🕷️" },
    { description: "spider web", emoji: "🕸️" },
    { description: "scorpion", emoji: "🦂" },
    { description: "sunflower", emoji: "🌻" },
    { description: "strawberry", emoji: "🍓" },
    { description: "sandwich", emoji: "🥪" },
    { description: "salt", emoji: "🧂" },
    { description: "spaghetti", emoji: "🍝" },
    { description: "shrimp", emoji: "🦐" },
    { description: "squid", emoji: "🦑" },
    { description: "spoon", emoji: "🥄" },
    { description: "school", emoji: "🏫" },
    { description: "skateboard", emoji: "🛹" },
    { description: "scooter", emoji: "🛴" },
    { description: "sailboat", emoji: "⛵" },
    { description: "ship", emoji: "🚢" },
    { description: "sun", emoji: "☀️" },
    { description: "star", emoji: "⭐" },
    { description: "snowflake", emoji: "❄️" },
    { description: "snowman", emoji: "☃️" },
    { description: "sunglasses", emoji: "🕶️" },
    { description: "scarf", emoji: "🧣" },
    { description: "socks", emoji: "🧦" },
    { description: "sari", emoji: "🥻" },
    { description: "shorts", emoji: "🩳" },
    { description: "shoe", emoji: "👞" },
    { description: "sandal", emoji: "👡" },
    { description: "saxophone", emoji: "🎷" },
    { description: "scissors", emoji: "✂️" },
    { description: "shield", emoji: "🛡️" },
    { description: "screwdriver", emoji: "🪛" },
    { description: "stethoscope", emoji: "🩺" },
    { description: "shower", emoji: "🚿" },
    { description: "soap", emoji: "🧼" },
    { description: "sponge", emoji: "🧽" },
  ],
  T: [
    { description: "thumbs up", emoji: "👍" },
    { description: "tooth", emoji: "🦷" },
    { description: "tongue", emoji: "👅" },
    { description: "teacher", emoji: "🧑‍🏫" },
    { description: "tiger", emoji: "🐅" },
    { description: "turkey", emoji: "🦃" },
    { description: "turtle", emoji: "🐢" },
    { description: "T-Rex", emoji: "🦖" },
    { description: "tulip", emoji: "🌷" },
    { description: "tangerine", emoji: "🍊" },
    { description: "tomato", emoji: "🍅" },
    { description: "teapot", emoji: "🫖" },
    { description: "teacup", emoji: "🍵" },
    { description: "tent", emoji: "⛺" },
    { description: "train", emoji: "🚆" },
    { description: "tram", emoji: "🚊" },
    { description: "taxi", emoji: "🚕" },
    { description: "tractor", emoji: "🚜" },
    { description: "timer", emoji: "⏲️" },
    { description: "thermometer", emoji: "🌡️" },
    { description: "tornado", emoji: "🌪️" },
    { description: "trophy", emoji: "🏆" },
    { description: "tennis", emoji: "🎾" },
    { description: "teddy bear", emoji: "🧸" },
    { description: "thread", emoji: "🧵" },
    { description: "t-shirt", emoji: "👕" },
    { description: "top", emoji: "👚" },
    { description: "top hat", emoji: "🎩" },
    { description: "trumpet", emoji: "🎺" },
    { description: "telephone", emoji: "☎️" },
    { description: "television", emoji: "📺" },
    { description: "toolbox", emoji: "🧰" },
    { description: "test tube", emoji: "🧪" },
    { description: "telescope", emoji: "🔭" },
    { description: "toilet", emoji: "🚽" },
    { description: "toothbrush", emoji: "🪥" },
  ],
  U: [
    { description: "unicorn", emoji: "🦄" },
    { description: "umbrella", emoji: "☂️" },
    { description: "up", emoji: "⬆️" },
  ],
  V: [
    { description: "vampire", emoji: "🧛" },
    { description: "volcano", emoji: "🌋" },
    { description: "volleyball", emoji: "🏐" },
    { description: "video game", emoji: "🎮" },
    { description: "violin", emoji: "🎻" },
  ],
  W: [
    { description: "woman", emoji: "👩" },
    { description: "wolf", emoji: "🐺" },
    { description: "whale", emoji: "🐋" },
    { description: "worm", emoji: "🪱" },
    { description: "watermelon", emoji: "🍉" },
    { description: "waffle", emoji: "🧇" },
    { description: "wood", emoji: "🪵" },
    { description: "watch", emoji: "⌚" },
    { description: "wheelchair", emoji: "🦽" },
    { description: "wave", emoji: "🌊" },
    { description: "wrench", emoji: "🔧" },
    { description: "window", emoji: "🪟" },
    { description: "white", emoji: "⚪" },
  ],
  X: [],
  Y: [
    { description: "yo-yo", emoji: "🪀" },
    { description: "yarn", emoji: "🧶" },
    { description: "yellow", emoji: "🟡" },
  ],
  Z: [
    { description: "zzz", emoji: "💤" },
    { description: "zebra", emoji: "🦓" },
  ],
};

export const getEmojisForLetter = (
  letter: string,
  maxNumberOfEmojis: number
): Emoji[] => {
  if (combinations[letter]) {
    const emojis = combinations[letter];
    return emojis.sort(() => 0.5 - Math.random()).slice(0, maxNumberOfEmojis);
  }

  return [];
};
